name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1 --nocapture
        env:
          DERIBIT_KEY: ${{ secrets.DERIBIT_KEY }}
          DERIBIT_SECRET: ${{ secrets.DERIBIT_SECRET }}
          RUST_BACKTRACE: 1
          RUST_LOG: deribit=warn